[manager]
linemode    = "size_and_mtime"
ratio       = [ 2, 3, 3 ]
show_hidden = true

[preview]
max-width=1200
max-height=1000

[opener]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true },
]
