---
promptToReturnFromSubprocess: false

keybinding:
  universal:
    edit: "o" # Change the edit action to 'o'

update:
  # One of: 'prompt' (default) | 'background' | 'never'
  method: prompt

  # Period in days between update checks
  days: 1

# tokyonight night / catppuccin-latte hybrid
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - "bold"
    inactiveBorderColor:
      - blue
    searchingActiveBorderColor:
      - yellow
      - "bold"
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#7297F1" # catppuccin-latte highlight blue
    cherryPickedCommitFgColor:
      - blue
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
